### PR TITLE
Add new course link

### PR DESCRIPTION
**Pull request by sailxjx**

### CODE REVIEW

**Comment by aishwaryanr** [comment]
Thank you for your contribution. I wasn't able to find any mention of Microsoft affiliation with the course. Could you provide more details on how it's connected to Microsoft? Is there any public information about this?

**Comment by sailxjx** [comment]
The content is based on microsoft's open sourced course https://github.com/microsoft/generative-ai-for-beginners
If you think it is unsuitable, maybe we can change the title to [Generative AI for Beginners](https://codekidz.ai/lesson-intro/generative-a-362093) By CodeKidz, based on Microsoft's open sourced course.

**Comment by aishwaryanr** [comment]
sure, can you please submit an update

**Comment by sailxjx** [comment]
@aishwaryanr done

**Pull request merged**
